### ISSUE TITLE
extracting prediction

### ISSUE THREAD

**Issue by khanyuriy** [MtDersvan/tf_playground#1]
Hi from Moscow! Thank you for tutorial! It is very helpfull!
Can you explain me, why  result_future.result().outputs['scores'] has shape [1,2] ? what does this two float_vals mean? And why you use np.argmax for extracting prediction?

>> print(result_future.result().outputs['scores'])
dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
float_val: 0.9468300938606262
float_val: 0.0531698614358902

**Comment by khanyuriy** [comment]
Ok, i think i got it
I have two prediction classes. One float_val per class. Each value is prediction for example of being member of that class.

**Comment by MtDersvan** [comment]
@khanyuriy Exactly! The `outputs['scores']` are NN outputs, were each one represents a unique class.
