### ISSUE TITLE
How can we use the trained model to query in python? can we use predict_classes()?

### ISSUE THREAD

**Issue by QaisarRajput** [MtDersvan/tf_playground#4]
How can we do prediction using the trained model in python? for testing we used `m.evaluate(input_fn=eval_input_fn, steps=1)`. is there a way we can use `predict_classes()` and `predict_proba()` the same way. ? as prediction does not need labels just features

**Comment by MtDersvan** [comment]
@QaisarRajput TenorFlow docs are very useful source of information like this. 
There is a `tensorflow.python.estimator.estimator.predict()` function that you can use. More information can be found here https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#predict
Something like this should exist for a tf 1.2.1 contrib version, too.

**Comment by MtDersvan** [comment]
@QaisarRajput Does this answers your question?

**Comment by QaisarRajput** [comment]
@MtDersvan Yes! i looked into it and was able to do the predictions. You can add this to the code if you want . For other people, what i added to the code is. 
```
predict_file = "adult.predict.csv"
df_predict = pd.read_csv(predict_file, names=COLUMNS, skipinitialspace=True)
def input_fn(df, predict = False):
    ...
    if predict == True:
        return feature_cols
    else:
        # Converts the label column into a constant Tensor.
        label = tf.constant(df[LABEL_COLUMN].values)
        return feature_cols, label

...

def predict_input_fn():
    return input_fn(df_predict, predict = True)
```

Then to do predictions. i made a csv in the same format as data. then ran the following code.
```
pre_results = m.predict_classes(input_fn=predict_input_fn)
pre_results_prob = m.predict_proba(input_fn=predict_input_fn)
for key,pro in zip(pre_results,pre_results_prob):
    print "%s : %s"%(key,[round(p,5) for p in pro])
```
The result looks like

```
0 : [0.80336, 0.19664]
0 : [0.61142, 0.38858]
0 : [0.79919, 0.20081]
1 : [0.00084, 0.99916]
0 : [0.85656, 0.14344]
0 : [0.74078, 0.25922]
0 : [0.75243, 0.24757]
0 : [0.55772, 0.44228]
```
Cheers!

**Comment by MtDersvan** [comment]
Awesome! The PR will be welcomed.
